### ISSUE TITLE
Invalid Result

### ISSUE THREAD

**Issue by samir2901** [tamojit2000/Integration-Solver-Fask#2]
![chrome_jlnlCXGQF5](https://user-images.githubusercontent.com/48079552/74103976-7fc40b80-4b76-11ea-89f3-85f99db378cf.png)
![ShareX_eUdQlC8Ci2](https://user-images.githubusercontent.com/48079552/74103977-80f53880-4b76-11ea-88f1-12d4ed2934e2.png)
Always showing invalid input.
Ar Play Store logo diyechis kno??

**Comment by tamojit2000** [comment]
Still in development
